### ISSUE TITLE
Automated builds & packaging

### ISSUE THREAD

**Issue by madisvain** [madisvain/upcount#10]
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by madisvain** [comment]
MacOS is done but missing the automated notarization part.

**Comment by mldev-py** [comment]
I've found that you had adjusted the workflow and changed env variables to CAPS. 👍 
Now, the MacOS notarization is still failed.
![noterr](https://user-images.githubusercontent.com/53791498/69107022-64ae9780-0a70-11ea-9706-fa981773f34f.png)
This could be related to the apple id password - we need to use the app-specific password, I think.
Please refer to the following link.
https://github.com/electron/electron-notarize/issues/15#issuecomment-546936371

**Comment by madisvain** [comment]
@mldev-py thank you for the suggestion - that was the correct fix. App-specific password.

The app now successfully builds on all platforms 🥇
