### ISSUE TITLE
add FR lang

### ISSUE THREAD

**Issue by kelvinhado** [madisvain/upcount#111]

**Comment by hrenard** [comment]
Look #97.

**Comment by kelvinhado** [comment]
Can you merge the PR for issue 97 or you are waiting for more validation? Thanks

**Comment by hrenard** [comment]
Unfortunately the maintainer doesn't seem active anymore... You can pull my fork for now.

**Comment by madisvain** [comment]
@kelvinhado @hrenard I'm very sorry for the repo getting a bit out of date. I will be doing maintenance on this over the weekend and I hope to have a release for all of you out quite soon

**Comment by hrenard** [comment]
Hey, great news ! 
Don't worry, nobody can expect software to be maintained for free. We're just happy when people do it. Maybe giving some access to another volunteer would help for the day to day maintaining : languages and dependencies updates.
