### ISSUE TITLE
what node version use ?

### ISSUE THREAD

**Issue by choupaland** [madisvain/upcount#134]
Hi,

Nice works.

I try to change the pdf template.

i try to `npm install `on node 16 , that doesn't work

i try after `npm install `on node 12.22.12, that "work"

but `npm run dist:dev` failed

`umi build` fail because umi it doesn't find

Which node version i need for `npm instal `and `umi build `work ?

Best regards.

**Comment by madisvain** [comment]
Project has switched from Electron to use Tauri.

There is a new alpha release out if you want to take a look: https://github.com/madisvain/upcount/releases/tag/v2.0.0-alpha.1

**Comment by choupaland** [comment]
why you change the entire stack ?
pass from umi/electron/js to react/tauri/ts ?

**Comment by PontusTideman** [comment]
> why you change the entire stack ? pass from umi/electron/js to react/tauri/ts ?

Much better workflow! See this link for comparison: [https://www.levminer.com/blog/tauri-vs-electron](url)
