### ISSUE TITLE
I can't export to PDF (after spending 1h creating the invoice!).

### ISSUE THREAD

**Issue by tuqueque** [madisvain/upcount#140]
Hello, I really like this program, is the only one that best approaches what I need, but it has a couple of bugs that are pretty much a deal breaker.

1.- It seems like I can't remove a logo/image in the Settings > Invoice.

2.- But the one that's a dealbreaker for me is that after spending like 1h creating an invoice, I click on the "PDF" button and absolutely nothing happens!

Also... Is this project still alive?... It seems like there hasn't been development for quite a while.

**Comment by madisvain** [comment]
@tuqueque sorry about your experience. The project indeed was in a sad state for a few years with no updates.

There is a new v2 coming out which is based on completely new technology. Not sure if you want to try the alpha version but soon enough you can check back to get a solid Invoicing application that will still be offline first and also include timetracking.

There will be an announcement on the [website](https://www.upcount.app/) once it's ready for public use.
