### ISSUE TITLE
MacOS raises an exception

### ISSUE THREAD

**Issue by madisvain** [madisvain/upcount#18]
<img width="532" alt="Screenshot 2019-11-20 22 15 31" src="https://user-images.githubusercontent.com/727994/69274638-71073180-0be3-11ea-959a-2dd4862d412d.png">

**Comment by mldev-py** [comment]
Fixed it by downgrading the electron version to 6.1.4

**Comment by madisvain** [comment]
Fixed by f9d3bad71f6800a73b8125f4e5a23e5c707f8096
