### ISSUE TITLE
Drag & Drop invoice lines

### ISSUE THREAD

**Issue by madisvain** [madisvain/upcount#19]
It should be possible to drag and drop invoice lines.

The UX logic should be as:
https://ant.design/docs/spec/direct#Drag-and-Drop

The fist icon for every line item should be:
<Icon type="more" />

When that icon is clicked and dragged the line can be dragged to a different order.

While dragging the icon:
<Icon type="drag" />

When you save the invoice the lines order is taken into account (this should already be so without modifications).

React library for drag & drop:
https://github.com/atlassian/react-beautiful-dnd

**Comment by madisvain** [comment]
There is a simple demo here:
https://ant.design/components/table/#components-table-demo-drag-sorting

But the hover should not always show the icon. The icon should only appear at the end of the line and when you click on the icon only then you can drag and drop.

**Comment by mldev-py** [comment]
![drag](https://user-images.githubusercontent.com/53791498/69399445-73a27d80-0cee-11ea-8842-b3752390a359.png)
So this means we can reorder the invoices by dragging and dropping the file-clip icon of every invoice line in `Invoices` view?
And the order should be saved always?

**Comment by mldev-py** [comment]
Oh, I think I've missed your requirement.
![lineitem](https://user-images.githubusercontent.com/53791498/69429879-dae32080-0d34-11ea-9143-e39430bfb8c0.png)
I believe you mean the above. Right? :)

**Comment by madisvain** [comment]
Yes - invoice lines should be possible to re-order :) So the last image is correct.

Lets just add the icon in front of every line:
<Icon type="more" />

So it's clear for the user where to click for the re-ordering.

**Comment by madisvain** [comment]
@mldev-py this is not a very important feature for now. Lets delay the development of this for a little while.

I will prepare a list of things we finalise before we do a public release so we can work on that next.

**Comment by mldev-py** [comment]
@madisvain 
Implemented by `pull request #26 `
First did this by using react-beautiful-dnd which is implemented in `invoices/line-items1.js` file.
But this occured a weird effect which seems to be related to redux-form.
So I've changed this by using react-dnd which is implemented in `invoices/line-items.js`
If you want to see the issue with react-beautiful-dnd, you can just rename the `line-items1.js` file into `line-items.js`

**Comment by madisvain** [comment]
Implemented by https://github.com/madisvain/upcount/pull/27
