### ISSUE TITLE
Printing bug

### ISSUE THREAD

**Issue by madisvain** [madisvain/upcount#22]
If you click on Print and then cancel then an error is thrown and printing will not work again until a refresh.

<img width="532" alt="Screenshot 2019-11-22 09 17 27" src="https://user-images.githubusercontent.com/727994/69407536-59c46300-0d0d-11ea-955d-e2937c64cc36.png">

**Comment by mldev-py** [comment]
This has been fixed with the pull request `22 - Printing bug` already. :)

**Comment by madisvain** [comment]
Fixed by 0fd3aa13d5904e0bfc119bdccdfa5b7d47e20687
