### ISSUE TITLE
Drag and Drop invoice lines issue

### ISSUE THREAD

**Issue by mldev-py** [madisvain/upcount#29]
@madisvain 
Currently, drag and drop has an issue.
If you drop on the input box, the input box is cleared. Please refer the following.

![dnd issue](https://user-images.githubusercontent.com/53791498/69952999-a6235600-14f8-11ea-8635-027094cd9519.gif)

Please refer #26 which I've made for dnd.
I've fixed the above issue in the #26 .
As well, I've followed the UX logic from https://ant.design/docs/spec/direct#Drag-and-Drop as you've mentioned.

**Comment by madisvain** [comment]
I think this was the fix you had right? https://github.com/madisvain/upcount/commit/a42e61241f18e337679c58819e0a48ce5c86d2cf

Thank you for this notice :)

**Comment by mldev-py** [comment]
Yep. No problem.
For the look and feel of the dnd, have you taken a look into my commit? :)
The look and feel is very similar to https://ant.design/docs/spec/direct#Drag-and-Drop
Thanks

**Comment by madisvain** [comment]
@mldev-py I did look and I did use the code and reviewed both examples you had. They were of big help actually. I'll review them again - I just want to finish the invoice templates refactoring I have and then make the first blog post about the app so we could get some initial traction and feedback to go forwards.

**Comment by mldev-py** [comment]
Cool. 👍
