### ISSUE TITLE
Change spelling of "payed" to "paid"

### ISSUE THREAD

**Issue by Neaox** [madisvain/upcount#31]
As per https://www.grammarly.com/blog/paid-payed/ all occurrences of "payed" should be changed to "paid"

**Comment by madisvain** [comment]
@Neaox thank you - the change will be made today and a new version released shortly. The app will auto-update itself after that.

**Comment by madisvain** [comment]
@Neaox the latest release [v0.2.1](https://github.com/madisvain/upcount/releases/tag/v0.2.1) fixed the spelling - the app should auto-update itself. Please let me know if you have any other issues or feature requests.
