### ISSUE TITLE
PDF bug

### ISSUE THREAD

**Issue by tobidsn** [madisvain/upcount#34]
Click on button PDF in preview and edit page error,
I install in Ubuntu 18

![image](https://user-images.githubusercontent.com/22290661/72218008-72f8cb80-3568-11ea-87ad-4899d789154f.png)

**Comment by madisvain** [comment]
@tobidsn I think this is now fixed with the newer versions. I tested tonight with 0.5.0 the latest release and got it to generate a PDF nicely on the Ubuntu 18.04 Virtualbox.

Please reopen the issue if this has not been resolved for you and I will dig deeper into this.

**Comment by Foriyo** [comment]
I am facing same issue on Ubuntu 20.04.2 LTS

**Comment by marcocastignoli** [comment]
me too
