### ISSUE TITLE
Logo Not displayed on Invoice

### ISSUE THREAD

**Issue by srameh** [madisvain/upcount#35]
The logo of the company is not added in the invoice, nor on the PDF.

**Comment by madisvain** [comment]
@srameh thank you for reporting this. The fix is in the latest release. The app should auto-update for you when you start it next time.

https://github.com/madisvain/upcount/releases/tag/v0.3.0

**Comment by srameh** [comment]
Thanks man. I got the update after starting the app. But The logo does not still show. Should I a clean install?

**Comment by madisvain** [comment]
No - can you provide me the logo you are using? I will test with the file you have.

**Comment by srameh** [comment]
You can use any image. I have tried several but no luck. I got the automatic update for the app as well but still the same. Below is the logo I used.
![logo](https://user-images.githubusercontent.com/4790053/74079975-0b934600-4a58-11ea-8374-3287cd7a6b44.png)

Also, is there a way to archive closed invoices or delete draft invoices?

**Comment by madisvain** [comment]
@srameh I can not currently reproduce this. The logo shows up just fine for me.
<img width="1112" alt="Screenshot 2020-02-09 09 57 02" src="https://user-images.githubusercontent.com/727994/74109742-be65c000-4b8e-11ea-901f-a43ad8f2d550.png">

Can you tell me what OS are you using?

**Comment by srameh** [comment]
Thanks for the reply. I will install it on a different machine and test it there. I will update you on the outcome.

**Comment by srameh** [comment]
It worked on a new machine.  Thank you!
![image](https://user-images.githubusercontent.com/4790053/74127513-ecc5b880-4beb-11ea-9f6a-864db5004a04.png)

**Comment by madisvain** [comment]
@srameh will close for now. If this pops up again feel free to open this again.
