### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by stgeipel** [madisvain/upcount#36]
I think it would be great to have internationalization. Users may want to work in their native language, which is not English

**Comment by madisvain** [comment]
@stgeipel yes this definitely is something that I want to add over the next week or two

**Comment by stgeipel** [comment]
perfekt. If you want i can translate into german

**Comment by stgeipel** [comment]
Perfect. I would translate it into German

**Comment by madisvain** [comment]
@stgeipel multilingual support has been released in the latest [v0.5.0](https://github.com/madisvain/upcount/releases/tag/v0.5.0) release.

I'd be very happy to add German translations if possible. The .po file to translate is located here:
https://github.com/madisvain/upcount/blob/master/src/locales/de/messages.po

You have also been added as a contributor:
https://github.com/madisvain/upcount#contributors

Thank you!
