### ISSUE TITLE
Phone number field issues in Organisation settings

### ISSUE THREAD

**Issue by feisar-uk** [madisvain/upcount#46]
When trying to enter a phone number in the Organization settings, the country code popup always goes back to +372.

Only after entering some numbers in the phone number field does the country code setting stay on what you select.

You then cannot delete the phone number by highlighting it all and pressing the delete key. It just unselects itself.

If you delete each character one-by-one you can delete all but the first digit. You cannot completely clear the field.

macOS 10.14.6

**Comment by madisvain** [comment]
@feisar-uk yes there seemed to be a issue in the phone input field. I have cleaned this up and will make a release today. This will be version 0.6 and it will provide you with an auto update quite soon.

Thank you very much for reporting this issue! 👍

**Comment by madisvain** [comment]
@feisar-uk the release has been made and is numbered 0.6.0.

Please let me know if you have any further issues but I hope this solves your use case.
