### ISSUE TITLE
Homepage Buttons open wrong URL

### ISSUE THREAD

**Issue by stgeipel** [madisvain/upcount#55]
If I press one of the three buttons I will be redirected to a wrong url.
A 404 from Github appears

**Comment by madisvain** [comment]
@stgeipel this is related to the https://www.upcount.app/ website?

**Comment by stgeipel** [comment]
yes. But now it works. 
Yesterday the URL look like : https://github.com/madisvain/upcount/releases/download/v0.6.0/Upcount-null.dmg
and not 
https://github.com/madisvain/upcount/releases/download/v0.6.0/Upcount-0.6.0.dmg

I'm closing this issue.
