### ISSUE TITLE
Apply default invoice setting

### ISSUE THREAD

**Issue by madisvain** [madisvain/upcount#6]
When creating a new invoice the default due days setting should set the due_date, currency, note automatically.

- [ ] due_date
- [ ] currency
- [ ] notes

**Comment by mldev-py** [comment]
As I see, when I create a new invoice, due_date and currency are set as the current date and `EUR` for now.
What should be the default notes?

**Comment by madisvain** [comment]
All the defaults should come from what the user has specified under Invoice settings.
<img width="1112" alt="Screenshot 2019-11-18 15 20 13" src="https://user-images.githubusercontent.com/727994/69055739-2cc73600-0a17-11ea-842c-66b5e8f83260.png">

If they are not set the defaults should be empty in the new invoice also.

**Comment by mldev-py** [comment]
Makes sense.
Thank you

**Comment by madisvain** [comment]
Fixed by 323598224d32f2a5b8551a7d68fc21357d515c31
