### ISSUE TITLE
Login/Register isn't working.

### ISSUE THREAD

**Issue by karimkkanji** [madisvain/upcount#65]
![image](https://user-images.githubusercontent.com/18611345/85118480-11304200-b229-11ea-926b-9c6c2927dba0.png)

Whenever I try to login, I get the above error when using DevTools to check for the error when registering on Upcount.

**Comment by madisvain** [comment]
@karimkkanji I have dropped this feature for now. Lets just continue with it as an offline-first solution and I'll add the possibility of making archives for backup in the next release.

The syncing solution got too difficult to maintain reliably and I'd like to keep Upcount as simple as possible to fill the needs of easy invoicing.

A new release version v0.8.0 has been released with all the latest updates.
