### ISSUE TITLE
Upcount v0.7.0 remains in the background even after Exit [ Windows ]

### ISSUE THREAD

**Issue by kanji-karanja** [madisvain/upcount#66]
Once I exit Upcount, it still remains in the background as a non visible process. 

![image](https://user-images.githubusercontent.com/18611345/85120103-708f5180-b22b-11ea-8563-bdb2f3ed217d.png)

The above screen shot is in Task Manager showing that Upcount is running but in the background even after exiting the app.

This in turn leads to organisations not loading when I resume the Application by opening it again.

**Comment by madisvain** [comment]
@karimkkanji sorry for the very long delay - this has been released in the v0.8.0 release.
