### ISSUE TITLE
Tax total and currency format

### ISSUE THREAD

**Issue by Awilson089** [madisvain/upcount#70]
Hi, thanks for the work on the app!

- Could the tax line not show when no tax is selected? 
- Also the pound sign should be before the total but at the moment it shows after.

Cheers

![image](https://user-images.githubusercontent.com/3376056/86130468-1a989480-badc-11ea-8bda-3dbe730b53f2.png)

**Comment by kai-oswald** [comment]
Agreed. Tax should not be shown when zero.

**Comment by madisvain** [comment]
@Awilson089 the currencies are now formatted according to the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat that also take into account the language/locale you are using together with the currency.

@kai-oswald yes the 0 tax I will remove in the next release probably this week the latest.
