### ISSUE TITLE
Currency not updated in Create Invoice page and All Invoices page

### ISSUE THREAD

**Issue by apurva92** [madisvain/upcount#79]
While creating a new invoice, there is an option to choose the currency and in the Settings there is an option to choose a default currency. However, the Create Invoice page still displays the currency as $ for "Subtotal" text field, Subtotal label, tax label and the the total amount label. Instead of $, the chosen currency should appear in all these places.

In the Invoices page, where all created invoices are displayed, there also the currency is shown as $ instead of the default / chosen currency.

The final invoice PDF shows the correct chosen currency.

<img width="1279" alt="Screen Shot 2020-10-06 at 5 29 31 PM" src="https://user-images.githubusercontent.com/5263250/95199061-dcf18900-07f9-11eb-9279-ca022b0c7927.png">
<img width="1279" alt="create_invoice" src="https://user-images.githubusercontent.com/5263250/95199067-df53e300-07f9-11eb-9b55-f7be2122be50.png">

**Comment by madisvain** [comment]
@apurva92 thank you very much for your bug report. The issue has been fixed in the latest release 0.8.3 the app should offer an auto update for you.

If you experience any further issues please let me know and thank you again!
