### ISSUE TITLE
Print button not working from invoice detail view

### ISSUE THREAD

**Issue by madisvain** [madisvain/upcount#8]
In the preview form there is logic in place to print the iFrame content only. That is so that the iFrame site can be styled separately and nothing else will influence it.

If possible I'd like to have the same print button also working from the invoice detail view. It should just open up the preview and print automatically. Even better would be if this could be done in the background so the preview view is not opened and we could just launch the iFrame printing from the background.

**Comment by mldev-py** [comment]
window.print() feature only works once in electron.
Have you tried to print the page more than once before?
Please refer https://github.com/electron/electron/issues/14705
This is an old issue of Electron.
As well, window.print() provides print to pdf feature so we don't need a separate pdf feature if we use this.
But this doesn't work actually. Please try the app.
The other way I've found is to use webContents.print() function.
And need some configuration with this, I think.
Any thoughts?

**Comment by madisvain** [comment]
@mldev-py what if we just implement the PDF feature: https://github.com/madisvain/upcount/issues/15

And we do not implement the Print feature at all. You can download the PDF open in your OS and print it after that.

**Comment by mldev-py** [comment]
Ah, that makes sense.
Got you.
One more question.
When you say `details view`
![detail](https://user-images.githubusercontent.com/53791498/69056480-592b8400-0a10-11ea-98d6-06a338341fb4.png)
And when you say `preview`
![preview](https://user-images.githubusercontent.com/53791498/69056500-65afdc80-0a10-11ea-8ed2-92776227bc8a.png)
Right?

**Comment by madisvain** [comment]
@mldev-py yes correct 👍

**Comment by madisvain** [comment]
Fixed by: edc6ad90fc7da7593097b40b9bdc58672f6b7dc8
