### ISSUE TITLE
Bug: NaN values in invoice 

### ISSUE THREAD

**Issue by GEDDE5** [madisvain/upcount#81]
I played around extensively and no matter how I go about it, I'm encountering [NaN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN) values in the following invoice fields: Sum, Subtotal, Tax, and Total. This does not occur in the Edit mode but does in View mode as well as in PDFs. 

Edit state:

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/564340/95379739-a0299e80-089a-11eb-9837-b1f714e24765.png">

Result:

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/564340/95379762-a91a7000-089a-11eb-82f4-286c147ebb36.png">

I notice that if I adjust the Subtotal field manually, in the Edit mode, the price will also display as NaN, while the Sum displays properly. 

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/564340/95379809-b9324f80-089a-11eb-8f80-765a25850fbf.png">

**Comment by madisvain** [comment]
@GEDDE5 sorry for your issue - the app should update itself to the newest version 0.8.3 when you re-open it. Have the issues you are experiencing been resolved there?

**Comment by madisvain** [comment]
@GEDDE5 for the invoices that still have the issue in the preview or PDF output please remove the currency symbol from the Invoice edit view and save the Invoice again.

It will recalculate the totals and the Invoice will render correctly in the preview and PDF now also.

Feel free to re-open the issue if the issues persist.

**Comment by GEDDE5** [comment]
> @GEDDE5 sorry for your issue - the app should update itself to the newest version 0.8.3 when you re-open it. Have the issues you are experiencing been resolved there?

All good now, yep; thank you
